### ISSUE TITLE
ONP?

### ISSUE THREAD

**Issue by jamOne-** [tjur/TestowanieOprogramowaniaJavaKalkulatorONP#1]
Co to za spadek formy?
Jeszcze niedawno robiłeś zaawansowane interpretery w Racketcie, a teraz jakaś Java 😭

**Comment by tjur** [comment]
Spokojnie 😄. To tylko skopiowane zadanie z kursu Javy z III semestru na potrzeby zabawy z Jenkinsem 😄 Tak naprawdę w domu potajemnie kodzę w COBOLu.
